### ISSUE TITLE
import() fails when using CommonJS version

### ISSUE THREAD

**Issue by nzakas** [humanwhocodes/module-importer#6]
Rollup is replacing `import()` with `require()`, which causes an error when attempting to import an ESM module from a CommonJS module.

**Comment by JounQin** [comment]
Hi, what is the difference with `import(specifier)` directly?

**Comment by nzakas** [comment]
Sorry, I’m not sure what you’re asking.

**Comment by JounQin** [comment]
> Sorry, I’m not sure what you’re asking.

Sorry if my question is confusing.

I'm just wondering what problem is this module resolving. 🤣
